#!/bin/bash

# Autodetect JAVA_HOME if not defined
if [ -e /usr/libexec/bigtop-detect-javahome ]; then
  . /usr/libexec/bigtop-detect-javahome
elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
  . /usr/lib/bigtop-utils/bigtop-detect-javahome
fi

export HADOOP_HOME=${HADOOP_HOME:-/usr/local/hadoop}
export HADOOP_LIBEXEC_DIR=${HADOOP_HOME}/libexec

exec /usr/local/hadoop/bin/hadoop "$@"
